// Convex database and scheduling constants
export const MEMOIR_GENERATION_DELAY = 7 * 1000; // 7 seconds in milliseconds

// Database table names
export const TABLES = {
  USERS: "users",
  WHISPERS: "whispers",
  MEMOIRS: "memoirs",
  SCHEDULED_MEMOIR_GENERATION: "scheduledMemoirGeneration",
} as const;

// Database index names
export const INDEXES = {
  BY_CLERK_ID: "by_clerk_id",
  BY_USER: "by_user",
  BY_WHISPER: "by_whisper",
  BY_MEMOIR_PUBLIC: "by_memoir_public",
  BY_PUBLIC: "by_public",
} as const;

// Error messages
export const ERROR_MESSAGES = {
  NOT_AUTHENTICATED: "Not authenticated",
  USER_NOT_FOUND: "User not found",
  WHISPER_NOT_FOUND: "Whisper not found",
  UNAUTHORIZED: "Unauthorized",
  MEMOIRS_NOT_PUBLIC: "User's memoirs are not public",
  FAILED_TO_SCHEDULE: "Failed to schedule memoir generation",
  FAILED_TO_CANCEL: "Failed to cancel scheduled function",
} as const;

// Status values
export const STATUS = {
  ACTIVE: "active",
  PROCESSING: "processing",
  INACTIVE: "inactive",
  FAILED: "failed",
} as const;

// ISO 639-1 Language codes and descriptions
export const LANGUAGES = {
  EN: { code: "en", name: "English", description: "English language" },
  ZH: { code: "zh", name: "Chinese", description: "Chinese language" },
  DE: { code: "de", name: "German", description: "German language" },
  ES: { code: "es", name: "Spanish", description: "Spanish language" },
  RU: { code: "ru", name: "Russian", description: "Russian language" },
  KO: { code: "ko", name: "Korean", description: "Korean language" },
  FR: { code: "fr", name: "French", description: "French language" },
  JA: { code: "ja", name: "Japanese", description: "Japanese language" },
  PT: { code: "pt", name: "Portuguese", description: "Portuguese language" },
  TR: { code: "tr", name: "Turkish", description: "Turkish language" },
  PL: { code: "pl", name: "Polish", description: "Polish language" },
  CA: { code: "ca", name: "Catalan", description: "Catalan language" },
  NL: { code: "nl", name: "Dutch", description: "Dutch language" },
  AR: { code: "ar", name: "Arabic", description: "Arabic language" },
  SV: { code: "sv", name: "Swedish", description: "Swedish language" },
  IT: { code: "it", name: "Italian", description: "Italian language" },
  ID: { code: "id", name: "Indonesian", description: "Indonesian language" },
  HI: { code: "hi", name: "Hindi", description: "Hindi language" },
  FI: { code: "fi", name: "Finnish", description: "Finnish language" },
  VI: { code: "vi", name: "Vietnamese", description: "Vietnamese language" },
  HE: { code: "he", name: "Hebrew", description: "Hebrew language" },
  UK: { code: "uk", name: "Ukrainian", description: "Ukrainian language" },
  EL: { code: "el", name: "Greek", description: "Greek language" },
  MS: { code: "ms", name: "Malay", description: "Malay language" },
  CS: { code: "cs", name: "Czech", description: "Czech language" },
  RO: { code: "ro", name: "Romanian", description: "Romanian language" },
  DA: { code: "da", name: "Danish", description: "Danish language" },
  HU: { code: "hu", name: "Hungarian", description: "Hungarian language" },
  TA: { code: "ta", name: "Tamil", description: "Tamil language" },
  NO: { code: "no", name: "Norwegian", description: "Norwegian language" },
  TH: { code: "th", name: "Thai", description: "Thai language" },
  UR: { code: "ur", name: "Urdu", description: "Urdu language" },
  HR: { code: "hr", name: "Croatian", description: "Croatian language" },
  BG: { code: "bg", name: "Bulgarian", description: "Bulgarian language" },
  LT: { code: "lt", name: "Lithuanian", description: "Lithuanian language" },
  LA: { code: "la", name: "Latin", description: "Latin language" },
  MI: { code: "mi", name: "Maori", description: "Maori language" },
  ML: { code: "ml", name: "Malayalam", description: "Malayalam language" },
  CY: { code: "cy", name: "Welsh", description: "Welsh language" },
  SK: { code: "sk", name: "Slovak", description: "Slovak language" },
  TE: { code: "te", name: "Telugu", description: "Telugu language" },
  FA: { code: "fa", name: "Persian", description: "Persian language" },
  LV: { code: "lv", name: "Latvian", description: "Latvian language" },
  BN: { code: "bn", name: "Bengali", description: "Bengali language" },
  SR: { code: "sr", name: "Serbian", description: "Serbian language" },
  AZ: { code: "az", name: "Azerbaijani", description: "Azerbaijani language" },
  SL: { code: "sl", name: "Slovenian", description: "Slovenian language" },
  KN: { code: "kn", name: "Kannada", description: "Kannada language" },
  ET: { code: "et", name: "Estonian", description: "Estonian language" },
  MK: { code: "mk", name: "Macedonian", description: "Macedonian language" },
  BR: { code: "br", name: "Breton", description: "Breton language" },
  EU: { code: "eu", name: "Basque", description: "Basque language" },
  IS: { code: "is", name: "Icelandic", description: "Icelandic language" },
  HY: { code: "hy", name: "Armenian", description: "Armenian language" },
  NE: { code: "ne", name: "Nepali", description: "Nepali language" },
  MN: { code: "mn", name: "Mongolian", description: "Mongolian language" },
  BS: { code: "bs", name: "Bosnian", description: "Bosnian language" },
  KK: { code: "kk", name: "Kazakh", description: "Kazakh language" },
  SQ: { code: "sq", name: "Albanian", description: "Albanian language" },
  SW: { code: "sw", name: "Swahili", description: "Swahili language" },
  GL: { code: "gl", name: "Galician", description: "Galician language" },
  MR: { code: "mr", name: "Marathi", description: "Marathi language" },
  PA: { code: "pa", name: "Punjabi", description: "Punjabi language" },
  SI: { code: "si", name: "Sinhala", description: "Sinhala language" },
  KM: { code: "km", name: "Khmer", description: "Khmer language" },
  SN: { code: "sn", name: "Shona", description: "Shona language" },
  YO: { code: "yo", name: "Yoruba", description: "Yoruba language" },
  SO: { code: "so", name: "Somali", description: "Somali language" },
  AF: { code: "af", name: "Afrikaans", description: "Afrikaans language" },
  OC: { code: "oc", name: "Occitan", description: "Occitan language" },
  KA: { code: "ka", name: "Georgian", description: "Georgian language" },
  BE: { code: "be", name: "Belarusian", description: "Belarusian language" },
  TG: { code: "tg", name: "Tajik", description: "Tajik language" },
  SD: { code: "sd", name: "Sindhi", description: "Sindhi language" },
  GU: { code: "gu", name: "Gujarati", description: "Gujarati language" },
  AM: { code: "am", name: "Amharic", description: "Amharic language" },
  YI: { code: "yi", name: "Yiddish", description: "Yiddish language" },
  LO: { code: "lo", name: "Lao", description: "Lao language" },
  UZ: { code: "uz", name: "Uzbek", description: "Uzbek language" },
  FO: { code: "fo", name: "Faroese", description: "Faroese language" },
  HT: {
    code: "ht",
    name: "Haitian Creole",
    description: "Haitian Creole language",
  },
  PS: { code: "ps", name: "Pashto", description: "Pashto language" },
  TK: { code: "tk", name: "Turkmen", description: "Turkmen language" },
  NN: { code: "nn", name: "Nynorsk", description: "Nynorsk language" },
  MT: { code: "mt", name: "Maltese", description: "Maltese language" },
  SA: { code: "sa", name: "Sanskrit", description: "Sanskrit language" },
  LB: {
    code: "lb",
    name: "Luxembourgish",
    description: "Luxembourgish language",
  },
  MY: { code: "my", name: "Myanmar", description: "Myanmar language" },
  BO: { code: "bo", name: "Tibetan", description: "Tibetan language" },
  TL: { code: "tl", name: "Tagalog", description: "Tagalog language" },
  MG: { code: "mg", name: "Malagasy", description: "Malagasy language" },
  AS: { code: "as", name: "Assamese", description: "Assamese language" },
  TT: { code: "tt", name: "Tatar", description: "Tatar language" },
  HAW: { code: "haw", name: "Hawaiian", description: "Hawaiian language" },
  LN: { code: "ln", name: "Lingala", description: "Lingala language" },
  HA: { code: "ha", name: "Hausa", description: "Hausa language" },
  BA: { code: "ba", name: "Bashkir", description: "Bashkir language" },
  JV: { code: "jv", name: "Javanese", description: "Javanese language" },
  SU: { code: "su", name: "Sundanese", description: "Sundanese language" },
  YUE: { code: "yue", name: "Cantonese", description: "Cantonese language" },
} as const;
